version: "3.9"

services:
  redis:
    image: redis:7
    ports:
      - "6379:6379"
    command: redis-server --stop-writes-on-bgsave-error no

  collector:
    build:
      context: ./collector
      dockerfile: Dockerfile
    ports:
      - "9094:9094"
    env_file:
      - ./collector/.env
    depends_on:
      - redis
    volumes:
      - ./sqlite.db:/app/posts.db

  management:
    build:
      context: ./management
      dockerfile: Dockerfile
    ports:
      - "9095:9094"
    env_file:
      - ./management/.env
    depends_on:
      - redis
    volumes:
      - ./sqlite.db:/app/posts.db

  gateway:
    build:
      context: ./gateway
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    env_file:
      - ./gateway/.env
    depends_on:
      - redis